version: '2'
services:
  healthcare_demo:
    build: 
      context: .
      target: healthcare_demo
    ports:
     - "5015:80"
    environment:
      APP_URL: "healthcare.marques.top"
      ASPNETCORE_URLS: "http://0.0.0.0:80"
      ASPNETCORE_ENVIRONMENT: "Production"

