version: '2'
services:
  healthcare_demo:
    restart: always
    build: 
      context: .
      target: healthcare_demo
    ports:
     - "5015:80"
    environment:
      APP_URL: "healthcare.marques.top"
      LETSENCRYPT_HOST: "healthcare.marques.top"
      VIRTUAL_HOST: "healthcare.marques.top"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: "Production"



